services:
  postgres:
    image: postgres:16
    container_name: critical-resource-db
    environment:
      POSTGRES_DB: critical_resource_db
      POSTGRES_USER: critical_user
      POSTGRES_PASSWORD: critical_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: